version: '3.9'

services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: bslr
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: bslr
    ports:
      - "5432:5432"

  matchmaking:
    build: ./backend/matchmaking-service
    ports:
      - "3001:3001"

  tournament:
    build: ./backend/tournament-service
    ports:
      - "3002:3002"

  anti-cheat:
    build: ./backend/anti-cheat-service
    ports:
      - "3003:3003"
