apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-workers

spec:
  replicas: 5

  template:
    spec:
      containers:
        - name: settlement-worker
          image: bslr/settlement-worker:latest
