name: Codespaces Prebuild

on:
  push:
    branches:
      - main

jobs:

  prebuild:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Containers
        run: docker compose build
