name: Codespaces Prebuild

on:
  push:
    branches:
      - main

jobs:

  prebuild:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build Dev Environment
        run: |
          docker-compose build
